### ISSUE TITLE
Including licensing terms into the template

### ISSUE THREAD

**Issue by yrashk** [LeadSV/rfc#1]
First of all, thank you for the effort! It's important to elevate the importance of RFC processes (and lightweight "formalisms") to help making better informed decisions and leaving an extensive record of thought, communication and commentary behind decision making process.

I am wondering what your thoughts are on nudging RFC authors to pick a license (and refer to it _within_ the RFC they are authoring) to avoid any potential licensing issues in the future?

Something that I'd like to refer on this matter is an opinion piece by late Pieter Hintjens http://hintjens.com/blog:41

**Comment by thecodedrift** [comment]
Sorry for the delay in commenting here. I think for open source communities it's a really important thing that RFCs (which often contain code) also include licensing for that code.

For RFC process internal to engineering organizations, this probably wouldn't apply because the terms of employment tend to cover the work folks generate as employees.

I'm happy to add a note to the readme since there's already a section on adapting this template.
